config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :prayers
  #get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prayer.rb
class Prayer < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :prayers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  before_action :set_prayer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /prayers or /prayers.json
  def index
    @prayers = Prayer.all
  end

  # GET /prayers/1 or /prayers/1.json
  def show
  end

  # GET /prayers/new
  def new
    @prayer = Prayer.new
  end

  # GET /prayers/1/edit
  def edit
  end

  # POST /prayers or /prayers.json
  def create
    @prayer = Prayer.new(prayer_params)

    respond_to do |format|
      if @prayer.save
        format.html { redirect_to @prayer, notice: "Prayer was successfully created."}
        format.json { render :show, status: :created, location: @prayer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prayers/1 or /prayers/1.json
  def update
    respond_to do |format|
      if @prayer.update(prayer_params)
        format.html { redirect_to @prayer, notice: "Prayer was successfully updated." }
        format.json { render :show, status: :ok, location: @prayer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prayers/1 or /prayers/1.json
  def destroy
    @prayer.destroy
    respond_to do |format|
      format.html { redirect_to prayers_url, notice: "Prayer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prayer
      @prayer = Prayer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prayer_params
      params.require(:prayer).permit(:prayer_request, :notes, :date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #9eca99;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">EverGreen</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Prayer Requests", prayers_path, class: "nav-link active" %>
        </li>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
  

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>EverGreen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class ="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/prayers/_form.html.erb
<%= form_with(model: prayer) do |form| %>
  <% if prayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prayer.errors.count, "error") %> prohibited this prayer from being saved:</h2>

      <ul>
        <% prayer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prayer_request %>
    <%= form.text_field :prayer_request %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id , id: :prayer_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prayers/edit.html.erb
<h1>Editing Prayer</h1>

<%= render 'form', prayer: @prayer %>

<%= link_to 'Show', @prayer %> |
<%= link_to 'Back', prayers_path %>

app/views/prayers/index.html.erb
<h1>Prayers</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Prayer request</th>
      <th>Notes</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prayers.each do |prayer| %>
      <% if current_user != nil and prayer.user_id == current_user.id %>  
        <tr>
          <td><%= prayer.prayer_request %></td>
          <td><%= prayer.notes %></td>
          <td><%= prayer.date %></td>
          <td><%= link_to 'Show', prayer %></td>
          <td><%= link_to 'Edit', edit_prayer_path(prayer) %></td>
          <td><%= link_to 'Delete', prayer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Prayer', new_prayer_path, class:"btn btn-success" %>

app/views/prayers/new.html.erb
<h1>New Prayer</h1>

<%= render 'form', prayer: @prayer %>

<%= link_to 'Back', prayers_path %>

app/views/prayers/show.html.erb
<p>
  <strong>Prayer request:</strong>
  <%= @prayer.prayer_request %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @prayer.notes %>
</p>

<p>
  <strong>Date:</strong>
  <%= @prayer.date %>
</p>

<%= link_to 'Edit', edit_prayer_path(@prayer) %> |
<%= link_to 'Back', prayers_path %>